owner: Truxnell
repo: upptime

sites:
  - name: Voltaicforge
    url: https://www.voltaicforge.com
  - name: k8s mkdoc
    url: https://k8s.voltaicforge.com
  - name: Status
    url: https://status.voltaicforge.com
  - name: Flux Webhook
    url: $URL_FLUX_WEBHOOK
    expectedStatusCodes:
      - 400
  - name: Plex
    url: $URL_PLEX
  - name: Home Assistant
    url: $URL_HOMEASSISTANT
  - name: Vaultwarden
    url: $URL_VAULTWARDEN
  - name: Joplin
    url: $URL_JOPLIN

assignees:
  - Truxnell

commitMessages:
  commitAuthorName: "Trux-Bot"
  commitAuthorEmail: "19149206+Truxnell@users.noreply.github.com"

status-website:
  cname: status.voltaicforge.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Hegira - Status
  theme: ocean
  introTitle: "**Hegira** cluster status & websites"
  introMessage: Current status of Hegira cluster / Voltaicforge websites
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: home-cluster GitHub
      href: https://github.com/Truxnell/home-cluster
    - title: k8s docs
      href: https://k8s.voltaicforge.com
    - title: Voltaicforge
      href: https://voltaicforge.com
