# Change these first
owner: Truxnell # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Voltaicforge
    url: https://www.voltaicforge.com
  - name: k8s mkdoc
    url: https://k8s.voltaicforge.com
  - name: Flux Webhook
    url: $URL_FLUX_WEBHOOK
    expectedStatusCodes:
      - 400
  - name: Plex
    url: $URL_PLEX
  - name: Home Assistant
    url: $URL_HOMEASSISTANT
  - name: Vaultwarden
    url: $URL_VAULTWARDEN
  - name: Joplin
    url: $URL_JOPLIN

assignees: # Users to assign downtime issues (optional)
  - Truxnell

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Hegira - Status
  introTitle: "**Hegira** cluster status & websites"
  introMessage: Current status of Hegira cluster / Voltaicforge websites
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
